<?xml version="1.0"?>
<robot name="differential_drive_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- Body dimensions -->
<xacro:property name="body_link_x_dim" value="1"/>
<xacro:property name="body_link_y_dim" value="0.6"/>
<xacro:property name="body_link_z_dim" value="0.3"/>

<!-- Wheels dimensions -->
<xacro:property name="wheel_link_radius" value="0.15"/>
<xacro:property name="wheel_link_length" value="0.1"/>
<xacro:property name="wheel_link_z_location" value="0.1"/>

<!--MAterial density -->
<xacro:property name="body_density" value="2710.0"/>
<xacro:property name="wheel_density" value="2710.0"/>

<!--pi constant -->
<xacro:property name="pi_constant" value="3.14159265"/>

<!--Robot body and wheel mass -->
<xacro:property name="body_mass" value="${body_density*body_link_x_dim*body_link_y_dim*body_link_z_dim}"/>
<xacro:property name="wheel_mass" value="${wheel_density*pi_constant*wheel_link_radius*wheel_link_radius*wheel_link_length}"/>

<!-- Moments of inertia of the wheel -->
<xacro:property name="Iz_wheel" value= "${0.5*wheel_link_radius*wheel_link_radius}"/>
<xacro:property name="I_wheel" value="${(1.0/12.0)*wheel_mass*(3.0*wheel_link_radius*wheel_link_radius+wheel_link_length*wheel_link_length)}" />

<!-- this macro defines the complete inertial section of the wheel -->
<xacro:macro name="inertia_wheel">
	<inertial>
	<origin rpy="0 0 0" xyz="0 0 0" />
	<mass value = "${wheel_mass}" />
	<inertia ixx="${I_wheel}" ixy="0.0" ixz="0.0" iyy="${I_wheel}" iyz="0" izz="${Iz_wheel}" />
	</inertial>
</xacro:macro>

<!-- plugins mass attributes for later use -->
<xacro:property name="camera_mass" value="0.1"/>
<xacro:property name="lidar_mass" value="1e-5"/>
<xacro:property name="imu_mass" value="1e-7"/>


<!-- include the file that defines extra gazebo opetions and motion control driver -->
<xacro:include filename="$(find rover_bot)/model/robot.gazebo" />





<!-- Remove this dummy part -->
<link name="dummy"/>
<joint name="dummy_joint" type="fixed">
  <parent link="dummy"/>
  <child link="body_link"/>
</joint>



<!-- BODY link -->

<link name="body_link">
	<visual>
		<geometry>
			<box size = "${body_link_x_dim} ${body_link_y_dim} ${body_link_z_dim}" />
		</geometry>
	<origin rpy="0 0 0" xyz="0 0 0" />
	</visual>
	
	<collision>
		<geometry>
			<box size = "${body_link_x_dim} ${body_link_y_dim} ${body_link_z_dim}" />
		</geometry>
		<origin rpy="0 0 0" xyz="0 0 0" />
	</collision>
	
	
	<inertial>
		<origin rpy ="0 0 0" xyz = "0 0 0" />
		<mass value= "${body_mass}" />
	<inertia 
	ixx="${(1.0/12.0)*body_mass*(body_link_y_dim*body_link_y_dim+body_link_z_dim*body_link_z_dim)}"
	ixy="0" ixz="0" iyy="${(1.0/12.0)*body_mass*(body_link_x_dim*body_link_x_dim+body_link_z_dim*body_link_z_dim)}"
	iyz="0" izz="${(1.0/12.0)*body_mass*(body_link_y_dim*body_link_y_dim+body_link_x_dim*body_link_x_dim)}" />
	
	</inertial>
</link>




<!--right back wheel of robot -->
 
 <joint name="wheel1_joint" type="continuous">
 	<parent link="body_link" />
 	<child link="wheel1_link" />
 	<origin xyz="${-body_link_x_dim/2+1.2*wheel_link_radius} ${-body_link_y_dim/2-wheel_link_length/2} ${-wheel_link_z_location}" rpy="0 0 0" />
 	<axis xyz="0 1 0" />
 	<limit effort="1000" velocity="1000" />
 	<dynamics damping="5.0" friction="5.0"/>

 </joint>
 
 <link name="wheel1_link">
 	<visual>
 		<origin rpy="1.570795 0 0" xyz="0 0 0" />
 		<geometry>
 			<cylinder length="${wheel_link_length}" radius="${wheel_link_radius}" />
 		</geometry>
 	</visual>
 	
 	<collision>
 		<origin rpy="1.570795 0 0" xyz="0 0 0" />
 		<geometry>
 			<cylinder length="${wheel_link_length}" radius="${wheel_link_radius}" />
 		</geometry>
 	</collision>
 	
 	<xacro:inertia_wheel />
 </link>



<!-- back left wheel -->

 <joint name="wheel2_joint" type="continuous">
 	<parent link="body_link" />
 	<child link="wheel2_link" />
 	<origin xyz="${-body_link_x_dim/2+1.2*wheel_link_radius} ${body_link_y_dim/2+wheel_link_length/2} ${-wheel_link_z_location}" rpy="0 0 0" />
 	<axis xyz="0 1 0" />
 	<limit effort="1000" velocity="1000" />
 	<dynamics damping="5.0" friction="5.0"/>

 </joint>
 
 <link name="wheel2_link">
 	<visual>
 		<origin rpy="1.570795 0 0" xyz="0 0 0" />
 		<geometry>
 			<cylinder length="${wheel_link_length}" radius="${wheel_link_radius}" />
 		</geometry>
 	</visual>
 	
 	<collision>
 		<origin rpy="1.570795 0 0" xyz="0 0 0" />
 		<geometry>
 			<cylinder length="${wheel_link_length}" radius="${wheel_link_radius}" />
 		</geometry>
 	</collision>
 	
 	<xacro:inertia_wheel />
 </link>




<!-- front right wheel -->

 <joint name="wheel3_joint" type="continuous">
 	<parent link="body_link" />
 	<child link="wheel3_link" />
 	<origin xyz="${body_link_x_dim/2-1.2*wheel_link_radius} ${-body_link_y_dim/2-wheel_link_length/2} ${-wheel_link_z_location}" rpy="0 0 0" />
 	<axis xyz="0 1 0" />
 	<limit effort="1000" velocity="1000" />
 	<dynamics damping="5.0" friction="5.0"/>

 </joint>
 
 <link name="wheel3_link">
 	<visual>
 		<origin rpy="1.570795 0 0" xyz="0 0 0" />
 		<geometry>
 			<cylinder length="${wheel_link_length}" radius="${wheel_link_radius}" />
 		</geometry>
 	</visual>
 	
 	<collision>
 		<origin rpy="1.570795 0 0" xyz="0 0 0" />
 		<geometry>
 			<cylinder length="${wheel_link_length}" radius="${wheel_link_radius}" />
 		</geometry>
 	</collision>
 	
 	<xacro:inertia_wheel />
 </link>




<!-- front left wheel -->

 <joint name="wheel4_joint" type="continuous">
 	<parent link="body_link" />
 	<child link="wheel4_link" />
 	<origin xyz="${body_link_x_dim/2-1.2*wheel_link_radius} ${body_link_y_dim/2+wheel_link_length/2} ${-wheel_link_z_location}" rpy="0 0 0" />
 	<axis xyz="0 1 0" />
 	<limit effort="1000" velocity="1000" />
 	<dynamics damping="5.0" friction="5.0"/>

 </joint>
 
 <link name="wheel4_link">
 	<visual>
 		<origin rpy="1.570795 0 0" xyz="0 0 0" />
 		<geometry>
 			<cylinder length="${wheel_link_length}" radius="${wheel_link_radius}" />
 		</geometry>
 	</visual>
 	
 	<collision>
 		<origin rpy="1.570795 0 0" xyz="0 0 0" />
 		<geometry>
 			<cylinder length="${wheel_link_length}" radius="${wheel_link_radius}" />
 		</geometry>
 	</collision>
 	
 	<xacro:inertia_wheel />
 </link>






<!-- lidar -->
<joint name="lidar_joint" type="fixed">
  <parent link="body_link"/>
  <child link="lidar_link"/>
  <origin xyz="0 0 0.17" rpy="0 0 0"/>
</joint>

<link name="lidar_link">
  <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <cylinder length="0.05" radius="0.05"/>
    </geometry>
    
  </visual>

  <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <cylinder length="0.05" radius="0.05"/>
    </geometry>
  </collision>

  <inertial>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <mass value="${lidar_mass}"/>
    <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/>
  </inertial>
</link>


	<joint name="camera_joint" type="fixed">
        <parent link="body_link"/>
        <child link="camera_link"/>
        <origin xyz="0.5 -0.25 0.1" rpy="0 0 0" />
    </joint>

    <link name="camera_link">
        <visual>
            <geometry>
                <box size="0.010 0.03 0.03" />
            </geometry>
        </visual>
    </link>



    <joint name="camera_optical_joint" type="fixed">
        <parent link="camera_link"/>
        <child link="camera_link_optical"/>
        <origin xyz="0 0 0" rpy="-1.5707 0 -1.5707" />
	</joint>

    <link name="camera_link_optical"></link>

<!--2nd camera-->

	<joint name="camera2_joint" type="fixed">
        <parent link="body_link"/>
        <child link="camera2_link"/>
        <origin xyz="0.5 0.25 0.1" rpy="0 0 0" />
    </joint>

    <link name="camera2_link">
        <visual>
            <geometry>
                <box size="0.010 0.03 0.03" />
            </geometry>
        </visual>
    </link>



    <joint name="camera2_optical_joint" type="fixed">
        <parent link="camera2_link"/>
        <child link="camera2_link_optical"/>
        <origin xyz="0 0 0" rpy="-1.5707 0 -1.5707" />
	</joint>

    <link name="camera2_link_optical"></link>




	<!-- Left camera frame -->
	<!-- <link name="left_camera_frame">
		<visual>
			<geometry>
			<box size="0.01 0.03 0.03"/>
			</geometry>
		</visual>
	</link>

	<joint name="left_camera_joint" type="fixed">
		<parent link="body_link"/>
		<child link="left_camera_frame"/>
		<origin xyz="0.5 -0.035 0.1" rpy="0 0 0" />
	</joint>

	<!- <joint name="left_camera_optical_joint" type="fixed">
        <parent link="left_camera_frame"/>
        <child link="left_camera_link_optical"/>
        <origin xyz="0 0 0" rpy="-1.5707 0 -1.5707" />
    </joint>

    <link name="left_camera_link_optical"></link> -->



	<!-- Right camera frame (optional for TF or visuals) -->
	<!-- <link name="right_camera_frame">
		<visual>
			<geometry>
				<box size="0.01 0.03 0.03"/>
			</geometry>
		</visual>
	</link>

	<joint name="right_camera_joint" type="fixed">
		<parent link="body_link"/>
		<child link="right_camera_frame"/>
		<origin xyz="0.5 0.035 0.1" rpy="0 0 0" />
	</joint> -->

	<!-- <joint name="right_camera_optical_joint" type="fixed">
        <parent link="right_camera_frame"/>
        <child link="right_camera_link_optical"/>
        <origin xyz="0 0 0" rpy="-1.5707 0 -1.5707" />
    </joint>

    <link name="right_camera_link_optical"></link> --> 


</robot>




